### ISSUE TITLE
Mac软件那些还是把链接删了吧

### ISSUE THREAD

**Issue by tesths** [MISSAJJ/MISSAJJ_IOS_DEVELOPMENT_BOOK#1]
毕竟盗版。中国的iOS开发环境很多都被盗版破坏了。你做开发你应该知道喵神书的事情，所以，自己用，推荐就行，链接就别放了吧...

**Comment by MISSAJJ** [comment]
你说的是那个现居日本的onevcat吗? 
抱歉,真不知道他发生了什么事情?

**Comment by tesths** [comment]
是的啊，他的书有人买了之后就放在网上肆意传播，根本不在乎作者的想法。而且那些盗版软件谁知道里面植入了什么程序，之前的iOS报过很多这种问题。

**Comment by MISSAJJ** [comment]
谢谢提醒
