### ISSUE TITLE
定义协议时，需要继承自 NSObjectProtocol，否则无法设置代理的类型

### ISSUE THREAD

**Issue by lycaste** [MISSAJJ/MISSAJJ_IOS_DEVELOPMENT_BOOK#2]
这句话 不太理解...

**Comment by MISSAJJ** [comment]
这句话是针对于 OC 和 Swift 设置代理的不同来说的
OC 中我们一般是这样定义的

``` objc
  @protocol VisitorViewDelegate  <NSObject>
```

Swift 定义代理 

``` Swift
 protocol VisitorViewDelegate: NSObjectProtocol
```

区别是: OC 继承的是NSObject, Swift 继承的是NSObjectProtocol,

在 Swift 中写错代理继承为 NSObject 会提示报错信息
Non-class type 'VisitorViewDelegate' cannot inherit from class 'NSObject'

**Comment by lycaste** [comment]
谢谢回复，但是还是不明白，你这个protocol为啥要继承这个NSObjectProtocol，是什么情况会出错

**Comment by lycaste** [comment]
语文不太好...大概就是什么情况下，需要这个协议 一定要继承自NSObjectProtocol

**Comment by MISSAJJ** [comment]
亲，Swift语言写代理就是继承NSObjectProtocol的，你若是写继承NSObject就直接报错了

这是Swift和OC的区别，建议你建个Swift项目实践一下，一试便知

Warm Regards，

纯子(^_~)☆MISSAJJ

https://github.com/MISSAJJ

**Comment by lycaste** [comment]
这个我知道。。。我写的代码 都是都不继承这个这个协议，我是想不通 为什么protocol要继承这个协议？他不是oc啊，一定要继承自nsobject。

**Comment by MISSAJJ** [comment]
因为:  是苹果官方这么定义和规定的, 请无须在此纠结和浪费时间....

请看苹果官方文档:  

```
The NSObject protocol groups methods that are fundamental to all Objective-C objects.

Note :  This protocol is imported into Swift with the name NSObjectProtocol.
```

官方文档链接地址:

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Protocols/NSObject_Protocol/index.html

**Comment by lycaste** [comment]
...这些都知道啊。我的意思是，是什么情况下，你的swift代码，一定要继承自这个NSObjectProtocol，我自己写的代码，还有我阅读的一些大型项目从来没遇到这种情况。还有“需要继承自 NSObjectProtocol，否则无法设置代理的类型”，这句话 我也不知道在什么情况下成立。不继承NSObjectProtocol，一样可以设置类型啊

**Comment by KieSun** [comment]
不需要明确表示继承自NSObjectProtocol，就像你写 OC 协议也不用明确表示继承自NSObject，两者都是相同的，只是在 Swift 里面改了个名字

**Comment by lycaste** [comment]
NSObjectProtocol 我只在swift-3-api-guidelines-review 这个项目中见到大量使用，在普通的swift代码中我觉得没有什么必要显示的声明这个NSObjectProtocol协议，也应该不存在“否则无法设置代理的类型”这种情况吧

**Comment by MISSAJJ** [comment]
亲, 

 "需要继承自 NSObjectProtocol，否则无法设置代理的类型",  这句话上边还有一段代码案例,是针对代码案例而写的注释,不能断章取义来理解.

之前我也已经申明了这句话仅是针对于区别: OC 继承的是NSObject, Swift 继承的是NSObjectProtocol

因为我学开发的时候还没有Swift, 一直写惯的是OC项目,所以初学Swift很容易习惯性写成NSObject,
而Swift中写错代理继承为OC中继承的`NSObject`会提示报错信息  
Non-class type 'VisitorViewDelegate' cannot inherit from class 'NSObject'

系统都报了错,标红了, 那还怎么继续写代理类型下去呢? 
所以才特地写了一个注释用来提醒

**Comment by lycaste** [comment]
因为我是看到你还有一句话**_需要注意的是，定义协议时，需要继承自 NSObjectProtocol**_才导致断章取义，而且swift的protocol真是没有必要声明为NSObjectProtocol

**Comment by MISSAJJ** [comment]
为了防止其他童鞋们误解, 所以已经将那段话修改了, 呵呵

**Comment by lycaste** [comment]
**_visitor-07-summary.md**_ 中措词还是不对,swift中的协议继承了 NSObjectProtocol和不继承 NSObjectProtocol意义完全不一样了,swift的protocol是完全没有任何必要去继承这个NSObjectProtocol，这和OC中写不写NSObject是俩个完全不同的俩个概念。这种protocol继承自 NSObjectProtocol写法，我没有找到没有任何官方依据,这种写法很不swifty

**Comment by MISSAJJ** [comment]
亲, 请查看一下官方Swift UIKit 内的 tableview 的代理协议申明写法, 官方的写法也是写了NSObjectProtocol, 这算是依据吗? 呵呵

```
public protocol UITableViewDelegate : NSObjectProtocol, UIScrollViewDelegate {

```

以下是官方 Swift  UIKit 内 UIViewController 内的写法

```
public protocol UIContentContainer : NSObjectProtocol {

public protocol UIViewControllerPreviewing : NSObjectProtocol {

public protocol UIViewControllerPreviewingDelegate : NSObjectProtocol {

public protocol UIPreviewActionItem : NSObjectProtocol {

public protocol UIContentContainer : NSObjectProtocol {

.......
```

**Comment by lycaste** [comment]
因为他是UIKit,整个UIKit的底层都是Objc的，就好比swift中的UIViewController继承NSObject那样。而一般的swift代码的protocol不需要，它们没有继承自NSObjectProtocol的必要，所以**_需要注意的是，定义协议时，需要继承自 NSObjectProtocol**_这句话完全是错误的，没有必要用OC的思维去思考swift

**Comment by MISSAJJ** [comment]
亲，都已经反复说了几遍，文中这句话是有上下文联系的，不能断章取义，咬文嚼字去理解。

笔记是对应小码哥新浪 Swift 项目的视频课程内容所记录，老师在视频教程里特地演示和好意提醒，仅是为了告诉我们在Swift中NSObject已经被改为NSObjectProtocol，旨在比较OC和Swift中协议的区别。

就好像老师告诉你小明已被改名为大明，就这么简单。

这里也有几篇写了NSObjectProtocol的案例：

http://www.tuicool.com/m/articles/6zEne2

http://blog.sina.cn/dpool/blog/s/blog_898847100102w00h.html?vt=4

至于写还是省略NSObjectProtocol都可以，完全由项目需求和个人决定，但不能单纯用错和对来判定。

苹果官方的SDK一直在升级修改，以前必写的说不定以后就不需要写了，方法过期了也会提示你用新的方法，但并不代表就错了。

非常感激你的留言，看得出来你是一个很认真严谨的开发者，咱们一起愉快地奔跑吧，呵呵……

Warm Regards，

纯子(^_~)☆MISSAJJ

https://github.com/MISSAJJ

**Comment by lycaste** [comment]
吊儿郎当菜鸟而已....

**Comment by gorain** [comment]
如果你想把一个 swift 的类实现一个 oc 的 protocol ，这个类必须实现 NSObjectProtocol ，跟改名啥的没关系，如果你声明一个 swift 的 protocol 而只有 swift 类实现它，你不需要让这个 protocol 继承自 NSObjectProtocol 。
NSObjectProtocol 实际是 OC 的历史包袱才存在的东西，如果是纯 Swift 的项目（我不是说在 iOS 中），你单独写一个完全与 OC 无关的 swift 项目，你会发现你将永远都不会用到这么个东西。
btw ， iOS 项目由于 cocoa 整个都是基于 oc runtime 的，所以你写的所有的 iOS / mac app 都将是与 oc 相关的。

**Comment by yishainchen** [comment]
The code above will give you the error if you forget to inherit from NSObjectProtocol. The reason being that weak only makes sense for reference types (classes). So you make the compiler less nervous by clearly stating that the PenguinDelegate is intended for classes, and not value types.
因為weak是用來reference types，所以Protocol繼承NSObjectProtocol是來告訴compiler説我的這個物件也是屬於reference types，如此一來在使用宣告delegate時才能透過採用weak來避免retain cycle。

link :https://stackoverflow.com/questions/38841127/why-can-the-keyword-weak-only-be-applied-to-class-and-class-bound-protocol-typ

**Comment by michaeldong** [comment]
> 如果你想把一个 swift 的类实现一个 oc 的 protocol ，这个类必须实现 NSObjectProtocol ，跟改名啥的没关系，如果你声明一个 swift 的 protocol 而只有 swift 类实现它，你不需要让这个 protocol 继承自 NSObjectProtocol 。
> NSObjectProtocol 实际是 OC 的历史包袱才存在的东西，如果是纯 Swift 的项目（我不是说在 iOS 中），你单独写一个完全与 OC 无关的 swift 项目，你会发现你将永远都不会用到这么个东西。
> btw ， iOS 项目由于 cocoa 整个都是基于 oc runtime 的，所以你写的所有的 iOS / mac app 都将是与 oc 相关的。

回答的直接，靠谱
